//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.13 at 09:27:23 PM CET 
//


package generatedClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="sendid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sendidexpr" type="{http://www.w3.org/2005/07/scxml}ValueLang.datatype" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "cancel")
public class Cancel {

    @XmlAttribute(name = "sendid", required = true)
    protected String sendid;
    @XmlAttribute(name = "sendidexpr")
    protected String sendidexpr;

    /**
     * Gets the value of the sendid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendid() {
        return sendid;
    }

    /**
     * Sets the value of the sendid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendid(String value) {
        this.sendid = value;
    }

    /**
     * Gets the value of the sendidexpr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendidexpr() {
        return sendidexpr;
    }

    /**
     * Sets the value of the sendidexpr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendidexpr(String value) {
        this.sendidexpr = value;
    }

}
