//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.13 at 09:27:23 PM CET 
//


package generatedClasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.w3.org/2005/07/scxml}elseif"/>
 *         &lt;element ref="{http://www.w3.org/2005/07/scxml}else"/>
 *         &lt;group ref="{http://www.w3.org/2005/07/scxml}executablecontent"/>
 *       &lt;/choice>
 *       &lt;attribute name="cond" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "elseifOrElseOrAssign"
})
@XmlRootElement(name = "if")
public class If {

    @XmlElements({
        @XmlElement(name = "elseif", type = Elseif.class),
        @XmlElement(name = "else", type = Else.class),
        @XmlElement(name = "assign", type = Assign.class),
        @XmlElement(name = "send", type = Send.class),
        @XmlElement(name = "if", type = If.class),
        @XmlElement(name = "log", type = Log.class),
        @XmlElement(name = "script", type = Script.class)
    })
    protected List<Object> elseifOrElseOrAssign;
    @XmlAttribute(name = "cond", required = true)
    protected String cond;

    /**
     * Gets the value of the elseifOrElseOrAssign property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the elseifOrElseOrAssign property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getElseifOrElseOrAssign().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Elseif }
     * {@link Else }
     * {@link Assign }
     * {@link Send }
     * {@link If }
     * {@link Log }
     * {@link Script }
     * 
     * 
     */
    public List<Object> getElseifOrElseOrAssign() {
        if (elseifOrElseOrAssign == null) {
            elseifOrElseOrAssign = new ArrayList<Object>();
        }
        return this.elseifOrElseOrAssign;
    }

    /**
     * Gets the value of the cond property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCond() {
        return cond;
    }

    /**
     * Sets the value of the cond property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCond(String value) {
        this.cond = value;
    }

}
