//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 10:41:11 AM CET 
//


package generatedClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="event" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="targettype" type="{http://www.w3.org/2005/07/scxml}targettype" default="scxml" />
 *       &lt;attribute name="sendid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="delay" type="{http://www.w3.org/2001/XMLSchema}string" default="'0s'" />
 *       &lt;attribute name="namelist" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="hints" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "send")
public class Send {

    @XmlAttribute(name = "event")
    protected String event;
    @XmlAttribute(name = "target")
    @XmlSchemaType(name = "anyURI")
    protected String target;
    @XmlAttribute(name = "targettype")
    protected Targettype targettype;
    @XmlAttribute(name = "sendid")
    protected String sendid;
    @XmlAttribute(name = "delay")
    protected String delay;
    @XmlAttribute(name = "namelist")
    protected String namelist;
    @XmlAttribute(name = "hints")
    protected String hints;

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvent(String value) {
        this.event = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarget(String value) {
        this.target = value;
    }

    /**
     * Gets the value of the targettype property.
     * 
     * @return
     *     possible object is
     *     {@link Targettype }
     *     
     */
    public Targettype getTargettype() {
        if (targettype == null) {
            return Targettype.SCXML;
        } else {
            return targettype;
        }
    }

    /**
     * Sets the value of the targettype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Targettype }
     *     
     */
    public void setTargettype(Targettype value) {
        this.targettype = value;
    }

    /**
     * Gets the value of the sendid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendid() {
        return sendid;
    }

    /**
     * Sets the value of the sendid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendid(String value) {
        this.sendid = value;
    }

    /**
     * Gets the value of the delay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelay() {
        if (delay == null) {
            return "'0s'";
        } else {
            return delay;
        }
    }

    /**
     * Sets the value of the delay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelay(String value) {
        this.delay = value;
    }

    /**
     * Gets the value of the namelist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamelist() {
        return namelist;
    }

    /**
     * Sets the value of the namelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamelist(String value) {
        this.namelist = value;
    }

    /**
     * Gets the value of the hints property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHints() {
        return hints;
    }

    /**
     * Sets the value of the hints property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHints(String value) {
        this.hints = value;
    }

}
