//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 10:41:11 AM CET 
//


package generatedClasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.w3.org/2005/07/scxml}onentry" minOccurs="0"/>
 *         &lt;element ref="{http://www.w3.org/2005/07/scxml}invoke" minOccurs="0"/>
 *         &lt;element ref="{http://www.w3.org/2005/07/scxml}transition" minOccurs="0"/>
 *         &lt;element ref="{http://www.w3.org/2005/07/scxml}initial" minOccurs="0"/>
 *         &lt;element ref="{http://www.w3.org/2005/07/scxml}state" minOccurs="0"/>
 *         &lt;element ref="{http://www.w3.org/2005/07/scxml}history" minOccurs="0"/>
 *         &lt;element ref="{http://www.w3.org/2005/07/scxml}parallel" minOccurs="0"/>
 *         &lt;element ref="{http://www.w3.org/2005/07/scxml}onexit" minOccurs="0"/>
 *         &lt;element ref="{http://www.w3.org/2005/07/scxml}datamodel" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="initial" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "onentryOrInvokeOrTransition"
})
@XmlRootElement(name = "state")
public class State {

    @XmlElements({
        @XmlElement(name = "onentry", type = Onentry.class),
        @XmlElement(name = "invoke", type = Invoke.class),
        @XmlElement(name = "transition", type = Transition.class),
        @XmlElement(name = "initial", type = Initial.class),
        @XmlElement(name = "state", type = State.class),
        @XmlElement(name = "history", type = History.class),
        @XmlElement(name = "parallel", type = Parallel.class),
        @XmlElement(name = "onexit", type = Onexit.class),
        @XmlElement(name = "datamodel", type = Datamodel.class)
    })
    protected List<Object> onentryOrInvokeOrTransition;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "initial")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> initial;

    /**
     * Gets the value of the onentryOrInvokeOrTransition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the onentryOrInvokeOrTransition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOnentryOrInvokeOrTransition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Onentry }
     * {@link Invoke }
     * {@link Transition }
     * {@link Initial }
     * {@link State }
     * {@link History }
     * {@link Parallel }
     * {@link Onexit }
     * {@link Datamodel }
     * 
     * 
     */
    public List<Object> getOnentryOrInvokeOrTransition() {
        if (onentryOrInvokeOrTransition == null) {
            onentryOrInvokeOrTransition = new ArrayList<Object>();
        }
        return this.onentryOrInvokeOrTransition;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the initial property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the initial property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInitial().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getInitial() {
        if (initial == null) {
            initial = new ArrayList<Object>();
        }
        return this.initial;
    }

}
